/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Presets
         * @description List the built-in example systems.
         */
        get: operations["get_presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get One Preset
         * @description Fetch a single preset by id.
         */
        get: operations["get_one_preset_api_presets__preset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Run a simulation and return the full trajectory + energy diagnostics.
         */
        post: operations["simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BodyIn */
        BodyIn: {
            /**
             * Mass
             * @description Mass in kilograms (must be positive).
             */
            mass: number;
            /**
             * Position
             * @description Position vector (2D or 3D).
             */
            position: number[];
            /**
             * Velocity
             * @description Velocity vector, same dim as position.
             */
            velocity: number[];
            /**
             * Name
             * @default Body
             */
            name: string;
            /**
             * Color
             * @default #FF0000
             */
            color: string;
        };
        /** BodyOut */
        BodyOut: {
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Mass */
            mass: number;
        };
        /** Energies */
        Energies: {
            /** Kinetic */
            kinetic: number[];
            /** Potential */
            potential: number[];
            /** Total */
            total: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PresetOut */
        PresetOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            request: components["schemas"]["SimRequest"];
        };
        /** SimRequest */
        SimRequest: {
            /** Bodies */
            bodies: components["schemas"]["BodyIn"][];
            /**
             * Duration
             * @description Total simulated time (seconds, or normalized units when G/length_unit are 1).
             */
            duration: number;
            /**
             * N Points
             * @default 1000
             */
            n_points: number;
            /**
             * Method
             * @default rk4
             * @enum {string}
             */
            method: "rk4" | "euler" | "verlet" | "scipy";
            /**
             * G
             * @description Gravitational constant (SI).
             * @default 6.6743e-11
             */
            G: number;
            /**
             * Length Unit
             * @description Meters per position unit (km -> 1000).
             * @default 1000
             */
            length_unit: number;
        };
        /** SimResponse */
        SimResponse: {
            /** Dim */
            dim: number;
            /** Method */
            method: string;
            /** Times */
            times: number[];
            /** Bodies */
            bodies: components["schemas"]["BodyOut"][];
            /** Positions */
            positions: number[][][];
            /** Velocities */
            velocities: number[][][];
            energies: components["schemas"]["Energies"];
            /** Energy Drift */
            energy_drift: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"][];
                };
            };
        };
    };
    get_one_preset_api_presets__preset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
